import express from 'express';
import { supabase } from '../server.js';

const router = express.Router();

// POST /api/exportar/zip - Export HTML page as ZIP
router.post('/zip', async (req, res) => {
  try {
    const { proyecto_id, html } = req.body;
    if (!html) return res.status(400).json({ error: 'html required' });

    // Dynamic import of JSZip (ESM)
    const { default: JSZip } = await import('jszip');
    const zip = new JSZip();
    zip.file('index.html', html);
    const buffer = await zip.generateAsync({ type: 'nodebuffer' });

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', 'attachment; filename="pagina-web.zip"');
    res.send(buffer);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// POST /api/exportar/wordpress - Export as WordPress theme ZIP
router.post('/wordpress', async (req, res) => {
  try {
    const { proyecto_id, html } = req.body;
    if (!html) return res.status(400).json({ error: 'html required' });

    const { data: proyecto } = await supabase.from('proyectos').select('nombre, chatbot_config').eq('id', proyecto_id).single();
    const nombre = proyecto?.chatbot_config?.nombre_negocio || proyecto?.nombre || 'mi-sitio';

    const { default: JSZip } = await import('jszip');
    const zip = new JSZip();
    const theme = zip.folder('pagegen-theme');

    // style.css (WP theme header)
    theme.file('style.css', `/*
Theme Name: ${nombre}
Theme URI: https://pagegen.ai
Description: Generated by pagegen.ai
Version: 1.0
*/`);

    // index.php
    theme.file('index.php', `<?php get_header(); ?>
<main id="main" class="site-main">
  ${html.replace(/<html[^>]*>|<\/html>|<head[^>]*>[\s\S]*?<\/head>|<body[^>]*>|<\/body>/gi, '')}
</main>
<?php get_footer(); ?>`);

    // functions.php
    theme.file('functions.php', `<?php
function pagegen_setup() {
  add_theme_support('title-tag');
  add_theme_support('post-thumbnails');
}
add_action('after_setup_theme', 'pagegen_setup');
?>`);

    // screenshot.png placeholder
    theme.file('header.php', '<?php wp_head(); ?>');
    theme.file('footer.php', '<?php wp_footer(); ?>');

    const buffer = await zip.generateAsync({ type: 'nodebuffer' });
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="pagegen-theme.zip"`);
    res.send(buffer);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

export default router;
